// Curated list of popular logo IDs surfaced first on the default home view.
// Order matters: items appear in this order at the top of the grid.
export const POPULAR_LOGO_IDS: string[] = [
  'zenobank',
  'bitcoin',
  'ethereum',
  'usdt',
  'xrp',
  'bnb',
  'solana',
  'usdc',
  'dogecoin',
  'toncoin',
  'cardano',
  'tron',
  'chainlink',
  'avalanche',
  'sui',
  'litecoin',
  'near',
  'polkadot',
  'aptos',
  'hyperliquid',
  'polygon',
  'arbitrum',
  'base',
  'optimism',
  'cosmos',
  'stellar',
  'monero',
  'uniswap',
  'aave',
  'maker',
  'lido',
  'celestia',
  'pepe',
  'jupiter',
  'pancakeswap',
  'binance',
  'coinbase',
  'metamask',
  'kraken',
  'okx',
  'bybit',
  'circle',
];

export const POPULAR_LOGO_ID_SET = new Set(POPULAR_LOGO_IDS);
